variables:
  image_size: &image_size 28
  n_classes: &n_classes 2
  
network:
  name: DoubleConvNet
  parameters: 
    in_shape: !!python/tuple [1, *image_size, *image_size]
    n_output: *n_classes
    in_features: 32
    out_features: 64
    alpha: 80

dataset:
  name: CBIS
  parameters:
    data_dir: /home/nvidia/projects/Research/AROB-CBIS-DDSM-Preparation/data/lesion/
    n_classes: *n_classes
    batch_size: 128
    resize: *image_size

encoder:
  name: PoissonEncoder
  module: norse.torch
  parameters:
    seq_length: 50

experiment:
  name: CBIS
  parameters:
    log_dir: ./logs
    seed: 1234
    epochs: 1
    lr: .001